name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s8z2n5e0

      - name: Build and push Docker image
        run: |
          docker build -t nginxhtml .
          docker tag nginxhtml:latest public.ecr.aws/s8z2n5e0/nginxhtml:latest
          docker push public.ecr.aws/s8z2n5e0/nginxhtml:latest

      - name: Update ECS servicedocker tag nginxhtml:latest public.ecr.aws/s8z2n5e0/nginxhtml:latest
        run: |
          aws ecs update-service --cluster myNginxCluster --service nginx-html-page --force-new-deployment
