name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 884211125288.dkr.ecr.ap-southeast-2.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t github-actions .
          docker tag github-actions:latest 884211125288.dkr.ecr.ap-southeast-2.amazonaws.com/github-actions:latest
          docker push 884211125288.dkr.ecr.ap-southeast-2.amazonaws.com/github-actions:latest

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster myNginxCluster --service nginx-html-page --force-new-deployment
